// <auto-generated />
namespace Infra.Logs.EF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBridgeTableForLogTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBridgeTableForLogTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201511222039232_AddBridgeTableForLogTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
